//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Pente.rc
//
#define IDC_AVAIL_MEM                   101
#define IDD_PENTE_DIALOG                102
#define IDC_PHYSICAL_MEM                102
#define IDC_AVAIL_VIRTUAL_MEM           103
#define IDC_CPU                         104
#define IDC_OS                          105
#define IDD_ABOUTDLG                    106
#define IDC_VERSION                     106
#define IDC_DISK_SPACE                  107
#define IDD_ABOUTDLG1                   107
#define IDM_ABOUT                       108
#define IDD_WAITWHITE                   110
#define IDR_MENU_CHINESE                122
#define IDR_MENU_ENGLISH                123
#define IDB_BLACK_STONE                 125
#define IDB_WHITE_STONE                 127
#define IDR_MAINFRAME                   128
#define IDB_FIVE                        128
#define IDDIB_BLACK                     129
#define IDC_BLACK_HAND                  130
#define IDDIB_BOARD                     130
#define IDC_WHITE_HAND                  131
#define IDDIB_MASK                      131
#define IDD_SETUPDLG                    131
#define IDDIB_WHITE                     132
#define IDR_MENU_CONTEXT_ENGLISH        132
#define IDR_ACCELERATOR                 133
#define IDSOUND_BLACK4                  133
#define IDR_MENU_CONTEXT_CHINESE        133
#define IDSOUND_BLACKD3                 134
#define IDSOUND_BLACKWIN                135
#define IDSOUND_ERROR                   136
#define IDD_RECORD1                     137
#define IDSOUND_GOODBYE                 137
#define IDSOUND_NEWGAME                 138
#define IDSOUND_PUTSTONE                139
#define IDSOUND_TIME                    140
#define IDSOUND_UNDO                    141
#define IDSOUND_WELCOME                 142
#define IDSOUND_WHITE4                  143
#define IDSOUND_WHITED3                 144
#define IDSOUND_WHITEWIN                145
#define IDD_DIAL                        156
#define IDC_NAME                        201
#define IDC_RED                         202
#define IDC_BLACK                       203
#define IDC_REDNAME                     204
#define IDC_LOCALCOLOR                  214
#define IDD_NETSTART                    503
#define IDD_LOCATEBLACK                 504
#define IDD_LOCATEBLACK1                505
#define IDD_NETSTART1                   506
#define IDD_WAITWHITE1                  507
#define IDD_MODEMSTART1                 508
#define IDD_MODEMSTART                  509
#define IDD_DIAL1                       510
#define IDD_BEST                        511
#define IDD_RECORD                      512
#define IDD_BEST1                       513
#define IDD_SETUPDLG1                   514
#define IDC_RADIO_DIAL                  1002
#define IDC_RADIO_ANSWER                1003
#define IDC_RED_MODEM                   1004
#define IDS_DISK_SPACE_UNAVAIL_CHINESE  1005
#define IDC_BLACK_MODEM                 1006
#define IDS_DISK_SPACE_CHINESE          1007
#define IDS_DISK_SPACE_UNAVAIL          1008
#define IDC_BROWSE                      1009
#define IDS_DISK_SPACE                  1009
#define IDC_RADIO_WITHCOMPUTER          1009
#define IDC_RADIO_2PLAYER               1010
#define IDC_RADIO_2PLAYER_NET           1011
#define IDS_AVAIL_MEM                   1012
#define IDC_RADIO_2PLAYER_MODEM         1012
#define IDS_SINGLE_COMPUTER_CHINESE     1013
#define IDC_RADIO_YOU_FIRST             1013
#define IDS_SINGLE_USER_CHINESE         1014
#define IDC_RADIO_COMPUTER_FIRST        1014
#define IDS_DOUBLE_CHINESE              1015
#define IDC_CHECK_SOUND                 1015
#define IDS_SINGLE_COMPUTER_ENGLISH     1016
#define IDC_TOTAL_SPACE                 1016
#define IDS_SINGLE_USER_ENGLISH         1017
#define IDC_FREE_SPACE                  1017
#define IDS_DOUBLE_ENGLISH              1018
#define IDS_NOSOUND_CHINESE             1019
#define IDS_NOSOUND_ENGLISH             1020
#define IDS_TITLE_CHINESE               1021
#define IDS_TITLE_ENGLISH               1022
#define IDS_BLACKWIN_ENGLISH            1023
#define IDS_BLACKWIN_CHINESE            1024
#define IDS_WHITEWIN_ENGLISH            1025
#define IDC_EDIT1                       1026
#define IDS_WHITEWIN_CHINESE            1026
#define IDC_EDIT2                       1027
#define IDS_TOTAL_CHINESE               1027
#define IDC_EDIT3                       1028
#define IDS_TOTAL_ENGLISH               1028
#define IDC_EDIT4                       1029
#define IDS_UNDO_CHINESE                1029
#define IDC_EDIT5                       1030
#define IDS_UNDO_ENGLISH                1030
#define IDC_EDIT6                       1031
#define IDS_CANNOT_UNDO_CHINESE         1031
#define IDS_CANNOT_UNDO_ENGLISH         1032
#define IDC_RESTARTCOUNT                1033
#define IDS_CANNOT_HINT_CHINESE         1033
#define IDS_CANNOT_HINT_ENGLISH         1034
#define IDS_DISK_SPACE_UNAVAIL2         1035
#define IDS_DISK_SPACE2                 1036
#define IDS_MATH_COPR_NOTPRESENT2       1037
#define IDS_MATH_COPR_PRESENT2          1038
#define IDS_CANNOT_UNDO_CHINESE1        1039
#define IDS_CANNOT_UNDO_ENGLISH1        1040
#define IDS_BEGINNER_CHINESE            1041
#define IDS_BEGINNER_ENGLISH            1042
#define IDS_INTERMEDIATE_CHINESE        1043
#define IDS_EXPERT_CHINESE              1044
#define IDS_INTERMEDIATE_ENGLISH        1045
#define IDS_EXPERT_ENGLISH              1046
#define IDS_MORE_CHINESE                1047
#define IDS_MORE_ENGLISH                1048
#define IDS_BAD_CHINESE                 1049
#define IDS_BAD_ENGLISH                 1050
#define IDS_DRAW_CHINESE                1051
#define IDS_DRAW_ENGLISH                1052
#define IDS_DOUBLE_NET_CHINESE          1053
#define IDS_DOUBLE_NET_ENGLISH          1054
#define IDS_IF_QUIT_CHINESE             1055
#define IDS_IF_QUIT_ENGLISH             1056
#define IDS_IF_NEW_CHINESE              1057
#define IDS_IF_NEW_ENGLISH              1058
#define IDS_IF_UNDO_CHINESE             1059
#define IDC_EDIT_DIAL_NUMBER            1060
#define IDS_IF_UNDO_ENGLISH             1060
#define IDS_DOUBLE_MODEM_CHINESE        1061
#define IDS_DOUBLE_MODEM_ENGLISH        1062
#define IDS_COLOR_LESS_CHINESE          1063
#define IDS_COLOR_LESS_ENGLISH          1064
#define IDS_ERROR_DISCONNECTED_ENGLISH  1069
#define IDS_ERROR_DISCONNECTED_CHINESE  1070
#define IDS_CHOOSE_BLACKCHESS_COMPUTER_NAME_ENGLISH 1071
#define IDS_CHOOSE_BLACKCHESS_COMPUTER_NAME_CHINESE 1072
#define IDM_NEW                         32769
#define IDM_EXIT                        32770
#define IDM_HINT                        32776
#define IDM_GRADE1                      32778
#define IDM_GRADE2                      32779
#define IDM_GRADE3                      32780
#define IDM_UNDO                        32781
#define IDM_LANGUAGE                    32782
#define IDM_BEST                        32784
#define IDM_HELP_CONTEXT                32786
#define IDM_SOUND                       32787

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        136
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1017
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
